### ISSUE TITLE
Extract reusable Stackdriver functionality into a common module

### ISSUE THREAD

**Issue by elefeint** [openzipkin/zipkin-gcp#139]
[`StackdriverSender`](https://github.com/openzipkin/zipkin-gcp/blob/master/sender-stackdriver/src/main/java/zipkin2/reporter/stackdriver/StackdriverSender.java) and [`StackdriverStorage`](https://github.com/openzipkin/zipkin-gcp/blob/master/storage-stackdriver/src/main/java/zipkin2/storage/stackdriver/StackdriverStorage.java) contain similar but subtly different implementations of talking to  and checking health of Stackdriver's `BatchWriteSpans` API.

Would it make sense to create a `stackdriver-common` module that both client and server-side functionality could depend on?

**Comment by adriancole** [comment]
I think we might end up with some dependency problems unless you are
thinking of using a few different parameters or otherwise. If the base has
no deps not already in both, it could make sense to reduce the amount of
test duplication. OTOH, we would then have another module to maintain which
is a bit more complex than not. the resulting types would be more complex
also.

three redundants are a lot easier to reason with common extraction than 2..
2 can go either way.
