### ISSUE TITLE
Propagate extra headers using propagation-keys

### ISSUE THREAD

**Issue by acet** [openzipkin/zipkin-gcp#167]
**Use Case**

We wish to propagate extra headers but the gcp implemenation of the zipkin sender does not support this.

**Details**

Using Spring Cloud Sleuth Trace Autoconfiguration at:
https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfiguration.java#L160
We can use the `ExtraFieldPropagation` to propagate fields in Sleuth as documented at:

https://cloud.spring.io/spring-cloud-sleuth/2.1.x/multi/multi__propagation.html 
"You can also use the spring.sleuth.propagation-keys property to pass a list of prefixed keys that are whitelisted without any prefix."

for example in an application properties file:
spring.sleuth.propagation-keys=country_code

Using Stackdriver Trace Autoconfiguration at:
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L225
the `StackdriverTracePropagation` is used which at:
https://github.com/openzipkin/zipkin-gcp/blob/master/propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/StackdriverTracePropagation.java#L64
does not allow the same ability to propagate extra fields.

Is it possible for `StackdriverTracePropagation` to be modified to allow extra headers to be propagated?

**Comment by elefeint** [comment]
@meltsufin FYI.

@acet Would you be interested in sending a pull request if you know what's needed here? If not, we'll investigate. I am a bit unsure why it does not work, since the extra field propagation seems like it's a decorator that's done in Brave regardless of the underlying delegate propagation. But I also have not looked at this code enough.

**Comment by adriancole** [comment]
what looks like to me is that customization was accomplished in sleuth via controlling the wrapping propagation component as opposed to the underlying one.

ex. instead of having a way to override the delegate (actual trace context impl, ex B3 or otherwise), it has a way to override the wrapper (extra field thingy)

So, any change would be in the spring-cloud-gcp project or spring-cloud-sleuth as the parts here shouldn't need to change IMHO.

**Comment by adriancole** [comment]
I will think about this more, too, just in case there's a way I'm not immediately thinking of..

**Comment by meltsufin** [comment]
We can close this one in favor of https://github.com/spring-cloud/spring-cloud-gcp/issues/2268.
