### ISSUE TITLE
zipkin.io/ tag prefix

### ISSUE THREAD

**Issue by crisbodnar** [openzipkin/zipkin-gcp#92]
I am using the `zipkin-collector` for sending traces to stackdriver. Annoyingly, the tags are prefixed with the `zipkin.io/` in the StackDriver Interface. How does that relate to the OpenTracing semantic conventions of the tags as the tags are modified? Is there a way to get rid of this? Is it still an issue in `zipkin-gcp`?

**Comment by adriancole** [comment]
I also dont like this prefix. let one other suggest we nix then nix it?
Better now before 1.0 cc @anuraaga

**Comment by teostoleru** [comment]
@crisbodnar @adriancole I've also run into this issue and would prefer the prefix to be removed.

**Comment by adriancole** [comment]
ok I will remove it now

**Comment by adriancole** [comment]
ok https://github.com/openzipkin/zipkin-gcp/pull/93

PS there are also some other bizarre things like how annotations are mapped to timestamps (I think this can be fixed by using stackdriver v2 model perhaps..) also, there's mapping of service to label component, and I think that's not a good name as service is not a component. Please raise issues for other strange things so that they are fixed prior to v1

**Comment by anuraaga** [comment]
`component` is probably a legacy from when these were components of the App Engine service (yeah), but unfortunately the Stackdriver Trace UI still uses it for the top level filtering / reporting so doubt we can change that.
