### ISSUE TITLE
Asymmetry in extractor vs injector breaks propagation

### ISSUE THREAD

**Issue by meltsufin** [openzipkin/zipkin-gcp#96]
The extractor always prioritizes GCP headers (`X-Cloud-Trace-Context`) over the Brave headers.
However, the injector only propagates traces in the Brave headers. The GCP load-balancer will generate `X-Cloud-Trace-Context` header when one is not present. This causes a break in the trace propagation from service A to B.

I see two possible solutions:
1. Injector should inject both `X-Cloud-Trace-Context` and `X-B3-*` headers.
2. Extractor should prioratize `X-B3-*` headers over `X-Cloud-Trace-Context`.

See: https://github.com/spring-cloud/spring-cloud-gcp/issues/1019

cc/ @saturnism

**Comment by adriancole** [comment]
ps "Brave headers" is a little imprecise probably a hundred libraries use
B3 :P

**Comment by adriancole** [comment]
I would recommend a couple things:

1. file a ticket with GCP load balancer to understand B3 headers.
Since many including census libraries also can send these as many
others sooner is better than later
2. I think your option of prioritizing B3 first will result in less
trace breaking because you can't control all the other libraries in
the ecosystem.
  * If you can, then you could prioritize as currently then
dual-propagate X-Cloud-Trace-Context

**Comment by adriancole** [comment]
I meant do both 1 and 2.

I maybe mis-phrased the bullet:
 * If you can, then you could prioritize as currently then
dual-propagate X-Cloud-Trace-Context

The sub-point to two was meant to be phrased unlikely. For example, it isn't likely to be in a homogenous `X-Cloud-Trace-Context`, hence this issue. It is even less likely going forward with tracecontext etc. So, prioritizing `X-Cloud-Trace-Context` (over b3) probably isn't much sense, and the incidental work dual-propagating `X-Cloud-Trace-Context` is also less sensible AFAICT.
